version: '3'
services:
  web:
    build: .
    restart: always
    ports:
      - "1337:1337"
    depends_on:
      - mongodb
    environment: 
      - DATABASE_NAME
      - DATABASE_URI
      - HEROKU_URL
      - DATABASE_SSL
    # volumes:
      # - ./webapp:/opt/webapp
  mongodb:
    image: mongo:latest
    volumes: 
      - /data/db
    ports:
      - "27017:27017"